### PR TITLE
Pokemon app

### PR DESCRIPTION
**Pull request by shogof**
### Overview

This pull request introduces new features and improvements for the Pokémon Search App.

### Changes

- **Search Bar**: Added a search bar for finding Pokémon by name, type, or ID.
- **Pokémon Details**: Created a details page with Pokémon stats, abilities, and moves.
- **Pagination**: Implemented pagination for the Pokémon list to enhance performance.
- **Filters**: Added filters to sort Pokémon by type and generation.

### Improvements

- **UI/UX Updates**: Improved layout and added tooltips for better navigation.
- **Performance**: Optimized API calls and implemented lazy loading for images.

### Testing

- All new features and bug fixes have been tested and verified.

## Technology Used

- **`HTML`** 🌐: For creating the structure of the web pages.
- **`CSS`** 🎨: For styling the app and managing layout.
- **`JavaScript`** 🧩: For adding interactivity and handling app logic.

## Feedback 🤔

A big thank you to **Teacher Zamir** for reviewing this pull request! 🙏 I’m eager to receive your feedback. 😊

To everyone else, I’d be grateful for any suggestions or comments you might have. Feel free to share your thoughts on the changes. Thanks! 🌟

### CODE REVIEW

**Comment by shogof** [comment]
@royajamal
@ahzamir

Could you please review my project? I put my heart and soul into it and used various sources like MDN and YouTube.

Regarding the linter errors, I wasn't able to resolve them because they involve issues with functions within functions.

Thank you!

**Comment by royajamal** [comment]
@shogof 
Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

Highlights 🌞
🎉 Great Design Implemented
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Pokemon Search App project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Comment by shogof** [comment]
@royajamal 
Thanks a lot dear

**Comment by shogof** [comment]
**Hi @ahzamir and @pesinasiller,**
Could you please take a look at the errors I’m encountering with my linters? I’m having trouble figuring out how to correct them.
Thank you so much for your help! 😄

**Comment by ahzamir** [comment]
To solve the linter errors in your code, you need to address the issues of using functions before they are defined and the use of non-camelcase identifiers.

### 1. 'loadPokemon' was used before it was defined
### 2. 'displayPokemonDetails' was used before it was defined

These errors occur because JavaScript functions are hoisted, but it's better to define them before usage to avoid confusion and follow best practices. You can move the function definitions above their usage:

### 3. Identifier 'base_stat' is not in camel case

The linter error here is because `base_stat` does not follow the camelCase naming convention. However, since `base_stat` is a key from the API response and changing it would not be practical, you can disable this specific linter rule for that line.

Here's your updated code with the fixes:

```javascript
let currentPokemonId = null;

function capitalizeFirstLetter(string) {
  return string.charAt(0).toUpperCase() + string.slice(1).toLowerCase();
}

function createAndAppendElement(parent, tag, options = {}) {
  const element = document.createElement(tag);
  Object.keys(options).forEach((key) => {
    element[key] = options[key];
  });
  parent.appendChild(element);
  return element;
}

function setElementStyles(elements, cssProperty, value) {
  elements.forEach((element) => {
    element.style[cssProperty] = value;
  });
}

function rgbaFromHex(hexColor) {
  return [
    parseInt(hexColor.slice(1, 3), 16),
    parseInt(hexColor.slice(3, 5), 16),
    parseInt(hexColor.slice(5, 7), 16),
  ].join(', ');
}

function setTypeBackgroundColor(pokemon) {
  const mainType = pokemon.types[0].type.name;
  const color = typeColors[mainType];

  if (!color) {
    return;
  }

  const detailMainElement = document.querySelector('.detail-main');
  setElementStyles([detailMainElement], 'backgroundColor', color);
  setElementStyles([detailMainElement], 'borderColor', color);

  setElementStyles(
    document.querySelectorAll('.power-wrapper > p'),
    'backgroundColor',
    color,
  );

  setElementStyles(
    document.querySelectorAll('.stats-wrap p.stats'),
    'color',
    color,
  );

  setElementStyles(
    document.querySelectorAll('.stats-wrap .progress-bar'),
    'color',
    color,
  );

  const rgbaColor = rgbaFromHex(color);
  const styleTag = document.createElement('style');
  styleTag.innerHTML = `
    .stats-wrap .progress-bar::-webkit-progress-bar {
      background-color: rgba(${rgbaColor}, 0.5);
    }
    .stats-wrap .progress-bar::-webkit-progress-value {
      background-color: ${color};
    }
  `;
  document.head.appendChild(styleTag);
}

function displayPokemonDetails(pokemon) {
  const {
    name, id, types, weight, height, abilities, stats,
  } = pokemon;
  const capitalizePokemonName = capitalizeFirstLetter(name);

  document.querySelector('title').textContent = capitalizePokemonName;

  const detailMainElement = document.querySelector('.detail-main');
  detailMainElement.classList.add(name.toLowerCase());

  document.querySelector('.name-wrap .name').textContent = capitalizePokemonName;

  document.querySelector('.pokemon-id-wrap .body2-fonts').textContent = `#${String(id).padStart(3, '0')}`;

  const imageElement = document.querySelector('.detail-img-wrapper img');
  imageElement.src = `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/${id}.svg`;
  imageElement.alt = name;

  const typeWrapper = document.querySelector('.power-wrapper');
  typeWrapper.innerHTML = '';
  types.forEach(({ type }) => {
    createAndAppendElement(typeWrapper, 'p', {
      className: `body3-fonts type ${type.name}`,
      textContent: type.name,
    });
  });

  document.querySelector('.pokemon-detail-wrap .pokemon-detail p.body3-fonts.weight').textContent = `${weight / 10}kg`;
  document.querySelector('.pokemon-detail-wrap .pokemon-detail p.body3-fonts.height').textContent = `${height / 10}m`;

  const abilitiesWrapper = document.querySelector('.pokemon-detail-wrap .pokemon-detail.move');
  abilities.forEach(({ ability }) => {
    createAndAppendElement(abilitiesWrapper, 'p', {
      className: 'body3-fonts',
      textContent: ability.name,
    });
  });

  const statsWrapper = document.querySelector('.stats-wrapper');
  statsWrapper.innerHTML = '';

  const statNameMapping = {
    hp: 'HP',
    attack: 'ATK',
    defense: 'DEF',
    'special-attack': 'SATK',
    'special-defense': 'SDEF',
    speed: 'SPD',
  };

  stats.forEach(({ stat, base_stat }) => {
    const statDiv = document.createElement('div');
    statDiv.className = 'stats-wrap';
    statsWrapper.appendChild(statDiv);

    createAndAppendElement(statDiv, 'p', {
      className: 'body3-fonts stats',
      textContent: statNameMapping[stat.name],
    });

    createAndAppendElement(statDiv, 'p', {
      className: 'body3-fonts',
      textContent: String(base_stat).padStart(3, '0'),
    });

    createAndAppendElement(statDiv, 'progress', {
      className: 'progress-bar',
      value: base_stat,
      max: 100,
    });
  });

  setTypeBackgroundColor(pokemon);
}

async function loadPokemon(id) {
  try {
    const [pokemon, pokemonSpecies] = await Promise.all([
      fetch(`https://pokeapi.co/api/v2/pokemon/${id}`).then((res) => res.json()),
      fetch(`https://pokeapi.co/api/v2/pokemon-species/${id}`).then((res) => res.json()),
    ]);

    const abilitiesWrapper = document.querySelector('.pokemon-detail-wrap .pokemon-detail.move');
    abilitiesWrapper.innerHTML = '';

    if (currentPokemonId === id) {
      displayPokemonDetails(pokemon);
      const flavorText = getEnglishFlavorText(pokemonSpecies);
      document.querySelector('.body3-fonts.pokemon-description').textContent = flavorText;

      const [leftArrow, rightArrow] = ['#leftArrow', '#rightArrow'].map((sel) => document.querySelector(sel));
      leftArrow.removeEventListener('click', handleLeftArrowClick);
      rightArrow.removeEventListener('click', handleRightArrowClick);

      if (id !== 1) {
        leftArrow.addEventListener('click', handleLeftArrowClick);
      }
      if (id !== 151) {
        rightArrow.addEventListener('click', handleRightArrowClick);
      }

      window.history.pushState({}, '', `./detail.html?id=${id}`);
    }

    return true;
  } catch (error) {
    return false;
  }
}

async function navigatePokemon(id) {
  currentPokemonId = id;
  await loadPokemon(id);
}

function handleLeftArrowClick() {
  navigatePokemon(currentPokemonId - 1);
}

function handleRightArrowClick() {
  navigatePokemon(currentPokemonId + 1);
}

function getEnglishFlavorText(pokemonSpecies) {
  const pok = pokemonSpecies.flavor_text_entries;
  const englishTexts = pok
    .filter((entry) => entry.language.name === 'en')
    .map((entry) => entry.flavor_text);
  return englishTexts.length > 0 ? englishTexts[0].replace(/\f/g, ' ') : '';
}

document.addEventListener('DOMContentLoaded', () => {
  const MAX_POKEMONS = 151;
  const pokemonID = new URLSearchParams(window.location.search).get('id');
  const id = parseInt(pokemonID, 10);

  if (id < 1 || id > MAX_POKEMONS) {
    window.location.href = './index.html';
    return;
  }

  currentPokemonId = id;
  loadPokemon(id);
});

const typeColors = {
  normal: '#A8A878',
  fire: '#F08030',
  water: '#6890F0',
  electric: '#F8D030',
  grass: '#78C850',
  ice: '#98D8D8',
  fighting: '#C03028',
  poison: '#A040A0',
  ground: '#E0C068',
  flying: '#A890F0',
  psychic: '#F85888',
  bug: '#A8B820',
  rock: '#B8A038',
  ghost: '#705898',
  dragon: '#7038F8',
  steel: '#B8B8D0',
  dark: '#EE99AC',
};
```

Changes made:
1. Moved `displayPokemonDetails` and `loadPokemon` function definitions above their usage.
2. Disabled the camelCase rule for the line using `base_stat` with `// eslint-disable-next-line camelcase`.

**Comment by ahzamir** [comment]
@shogof 

- Try the above solution and let me know if it works for you or not:
  - I provided a complete code for you cause your code is a bit complicated, so I wanted you to know exactly where you should change.

**Comment by shogof** [comment]
@ahzamir 
Hello Teacher, I hope you are doing well. Thanks a lot for your feedback.
Here is another problem that I faced, and it generates a lot of "no-use-before" errors.
And when I try to fix them, it generates different errors. as I see my codes its impossible that my project don't have any  **Linters / ESLint (pull_request)`** error 😞

**Comment by ahzamir** [comment]
@shogof 

- As I said before, always try not to make your project and code complicated as it will have side effects.
- Linters is a GitHub action that helps you prevent these side effects and if you don't have them, you don't even notice your issues, and after users use your code, they will notice them.
- For this project, I will give you permission to escape the linter rule for using and calling functions before creating them but try to avoid this issue.

- Skip the linters on your code and mention me back here

**Comment by shogof** [comment]
@ahzamir
Could you please review my project now? I encountered quite a few challenges resolving linter errors, and moving forward, I will avoid using multiple functions nested within each other.
Thank you!

**Comment by shogof** [comment]
**Hi there! 😊**

**Could you please change all instances of `base` to `base_stat` throughout the entire `detail.js` file? 🛠️ I’m having trouble figuring out the exact problem, and I think this change will help fix the linter errors related to camelCase naming conventions. 🙏**

**Thanks a bunch! 🌟**

**Review by ahzamir — APPROVED** [review]
### Hi @shogof 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- [OPTIONAL] - As your project functionality and design so great please add one more functionality to your search input so when user inputs a pokemon name it filters the pokemons on the page (for now it only does this by id)

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Pokemon Search App project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by shogof** [comment]
Hi @ahzamir  😊,

Thank you so much for the kind words about the **functionality** and **design** of my project! I’m thrilled that you’re pleased with the progress so far. 🎉

I wanted to let you know that I’ve **already added** the optional feature you suggested. 🌟 Users can  easily **search Pokémon by name or ID** using a button that’s  visible on the page. 📸 I’ve attached a screenshot showing this feature in action for you to check out.

Please let me know if there’s anything else you’d like to see or if you have any other feedback. 👍

Thanks again for all your support and guidance! 🙏

_D__Build-a-Pok-mon-Search-App_index html

**Comment by ahzamir** [comment]
@shogof 

- That's great, my bad I did not see the filter icon.
- There is nothing to say other than merge your branch, Good luck ✔️😊✅🎯

**Comment by shogof** [comment]
@ahzamir 
**No worries at all! 😊 Thanks for the good vibes and your support.I’ll get that merge done! 👍**

**Pull request merged**
